import { useCallback, useEffect, useRef, useState } from "react";
import type { FormEvent } from "react";
import { APP_NAME } from "@openslate/core/public";
import { ApiError, StudioApi } from "./api";
import { Connect, Icon, Lightbox, Preview, ShotCard, errorText } from "./components";
import { DirectorSettings } from "./DirectorSettings";
import { MediaPanel } from "./MediaPanel";
import { ImagePanel } from "./ImagePanel";
import { NarrationPanel } from "./NarrationPanel";
import { NewProjectProviderFields } from "./ProviderSettings";
import { SpendingPanel } from "./SpendingPanel";
import { canUseDemo, projectCreationCommand } from "./provider-model";
import type { NewProjectCommand, ProviderSelection, ProviderView } from "./provider-model";
import { approvalPayload, conversation, durationLabel, makeImageDiscussion, makeMessageCommand, makeQuestionReply, pollingDelay, reviewIdentity, reviewMatchesProject } from "./model";
import type { DirectorStatus, MessageCommand, ProjectSnapshot, ProjectSummary, ReviewSnapshot, Shot } from "./model";

const projectPath = (id: string) => `/api/projects/${encodeURIComponent(id)}`;
const offlineDirector: DirectorStatus = { mode: "offline", status: "not_connected" };
function useProject(api: StudioApi, projectId: string, refreshKey: number) {
  const [snapshot, setSnapshot] = useState<ProjectSnapshot | null>(null); const [review, setReview] = useState<ReviewSnapshot | null>(null);
  const [director, setDirector] = useState<DirectorStatus>(offlineDirector); const [connection, setConnection] = useState<"connecting" | "connected" | "reconnecting">("connecting"); const [error, setError] = useState("");
  const currentId = useRef(projectId);
  useEffect(() => {
    if (currentId.current !== projectId) { setSnapshot(null); setReview(null); setDirector(offlineDirector); currentId.current = projectId; }
    if (!projectId) return;
    const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>; let failures = 0; let lastSignature = "";
    setConnection("connecting");
    async function poll() {
      try {
        const [next, status] = await Promise.all([api.request<ProjectSnapshot>(projectPath(projectId), { signal: controller.signal }), api.request<DirectorStatus>(`${projectPath(projectId)}/director`, { signal: controller.signal })]);
        const signature = `${next.project.headVersion}:${next.project.activePlanId}:${next.cursor}`;
        if (signature !== lastSignature) { const nextReview = await api.request<ReviewSnapshot>(`${projectPath(projectId)}/review`, { signal: controller.signal }); if (controller.signal.aborted) return; setReview(nextReview); lastSignature = signature; }
        if (controller.signal.aborted) return;
        setSnapshot(next); setDirector(status); setConnection("connected"); setError(""); failures = 0;
      } catch (error) { if (controller.signal.aborted) return; failures++; setConnection("reconnecting"); setError(errorText(error)); }
      if (!controller.signal.aborted) timer = setTimeout(() => void poll(), pollingDelay(failures, document.hidden));
    }
    void poll(); return () => { controller.abort(); clearTimeout(timer); };
  }, [api, projectId, refreshKey]);
  return { snapshot: snapshot?.project.id === projectId ? snapshot : null, review: snapshot?.project.id === projectId ? review : null, director, connection, error };
}
type PendingMessage = { command: MessageCommand; failed: boolean };
type Action = { projectId: string; path: string; body: unknown; key: string; label: string };
function Studio({ api, initialProjects, disconnect }: { api: StudioApi; initialProjects: ProjectSummary[]; disconnect: () => void }) {
  const [projects, setProjects] = useState(initialProjects); const [projectId, setProjectId] = useState(initialProjects[0]?.id ?? "");
  const [refreshKey, setRefreshKey] = useState(0); const { snapshot, review, director, connection, error: connectionError } = useProject(api, projectId, refreshKey);
  const [pendingCreation, setPendingCreation] = useState<NewProjectCommand | null>(null);
  const [providerSelection, setProviderSelection] = useState<ProviderSelection | null>(null);
  const [demoProfiles, setDemoProfiles] = useState<{ projectId: string; allowed: boolean } | null>(null);
  const demoAvailable = demoProfiles?.projectId === projectId && demoProfiles.allowed;
  const [newName, setNewName] = useState(""); const [creating, setCreating] = useState(false); const [showNew, setShowNew] = useState(!initialProjects.length);
  const [showDirectorSettings, setShowDirectorSettings] = useState(false);
  const [selectedShots, setSelectedShots] = useState<string[]>([]); const [selectedReview, setSelectedReview] = useState<string[]>([]);
  const [displayed, setDisplayed] = useState<Record<string, string>>({}); const [reviewChanged, setReviewChanged] = useState(false);
  const [drafts, setDrafts] = useState<Record<string, string>>({}); const [pending, setPending] = useState<Record<string, PendingMessage>>({});
  const [pendingActions, setPendingActions] = useState<Record<string, Action>>({}); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState(""); const [actionError, setActionError] = useState("");
  const [tab, setTab] = useState<"storyboard" | "plan">("storyboard"); const [lightbox, setLightbox] = useState<{ url: string; shot: Shot; fixture: boolean | null } | null>(null);
  const selectionIdentity = useRef(""); const [replyQuestionId, setReplyQuestionId] = useState<string | null>(null);
  const lastReview = useRef(""); const chatEnd = useRef<HTMLDivElement>(null); const composer = useRef<HTMLTextAreaElement>(null);
  const refresh = useCallback(() => setRefreshKey(key => key + 1), []);
  const identity = reviewIdentity(review); const draft = drafts[projectId] ?? ""; const pendingMessage = pending[projectId]; const pendingAction = pendingActions[projectId];
  const connected = connection === "connected"; const staleReview = !connected || !reviewMatchesProject(review, snapshot); const messages = conversation(snapshot);
  useEffect(() => { setSelectedShots([]); setSelectedReview([]); setDisplayed({}); setFeedback(""); setActionError(""); setReviewChanged(false); setLightbox(null); setReplyQuestionId(null); selectionIdentity.current = ""; lastReview.current = ""; }, [projectId]);
  useEffect(() => { if (lastReview.current && lastReview.current !== identity) { setLightbox(null); if (selectedReview.length) { setSelectedReview([]); setReviewChanged(true); } } lastReview.current = identity; }, [identity, selectedReview.length]);
  useEffect(() => { if (snapshot) setSelectedShots(ids => ids.filter(id => snapshot.project.shots.some(shot => shot.id === id))); }, [snapshot]);
  useEffect(() => { chatEnd.current?.scrollIntoView({ block: "nearest", behavior: "auto" }); }, [messages.length, pendingMessage?.failed]);
  useEffect(() => {
    if (!projectId) return;
    const controller = new AbortController();
    void api.request<{ profiles: ProviderView[] }>(`${projectPath(projectId)}/providers`, { signal: controller.signal })
      .then(value => { if (!controller.signal.aborted) setDemoProfiles({ projectId, allowed: canUseDemo(value.profiles) }); })
      .catch(() => { if (!controller.signal.aborted) setDemoProfiles({ projectId, allowed: false }); });
    return () => controller.abort();
  }, [api, projectId, refreshKey]);
  async function reloadProjects() { const value = await api.request<{ projects: ProjectSummary[] }>("/api/projects"); setProjects(value.projects); }
  async function createProject(event: FormEvent) {
    event.preventDefault(); if (!newName.trim() || creating) return; setCreating(true); setActionError("");
    let command: NewProjectCommand;
    try { command = pendingCreation ?? projectCreationCommand(newName, crypto.randomUUID(), providerSelection); }
    catch (error) { setActionError(errorText(error)); setCreating(false); return; }
    setPendingCreation(command);
    try { const project = await api.request<ProjectSummary>("/api/projects", { method: "POST", body: command.body, key: command.key }); setPendingCreation(null); setProviderSelection(null); setProjects(all => [project, ...all.filter(item => item.id !== project.id)]); setProjectId(project.id); setNewName(""); setShowNew(false); setShowDirectorSettings(true); void reloadProjects().catch(() => {}); }
    catch (error) { if (error instanceof ApiError && !["NETWORK_ERROR", "INTERNAL_ERROR", "REQUEST_FAILED"].includes(error.code)) setPendingCreation(null); setActionError(errorText(error)); } finally { setCreating(false); }
  }
  async function send() {
    if (!snapshot || busy || pendingAction) return; let command: MessageCommand;
    try { const question = snapshot.questions?.find(item => item.id === replyQuestionId);
      if (replyQuestionId && !question) throw new Error("That question is no longer available. Refresh to continue.");
      command = pendingMessage?.command ?? (question ? makeQuestionReply(projectId, question, draft, crypto.randomUUID()) : makeMessageCommand(snapshot.project, draft, selectedShots, crypto.randomUUID(), director.mode === "native")); } catch (error) { setActionError(errorText(error)); return; }
    setBusy(true); setActionError(""); setPending(all => ({ ...all, [command.projectId]: { command, failed: false } }));
    try { await api.request(`${projectPath(command.projectId)}/messages`, { method: "POST", body: command.body, key: command.key }); setPending(all => { const next = { ...all }; delete next[command.projectId]; return next; }); setDrafts(all => ({ ...all, [command.projectId]: "" })); setReplyQuestionId(null); setFeedback("Message saved."); refresh(); }
    catch (error) { if (!(error instanceof ApiError) || ["NETWORK_ERROR", "INTERNAL_ERROR", "REQUEST_FAILED"].includes(error.code)) setPending(all => ({ ...all, [command.projectId]: { command, failed: true } })); else { setPending(all => { const next = { ...all }; delete next[command.projectId]; return next; }); if (error.code === "QUESTION_STALE") setReplyQuestionId(null); refresh(); } setActionError(errorText(error)); } finally { setBusy(false); }
  }
  async function runAction(action: Action) {
    if (busy) return; setBusy(true); setActionError(""); setFeedback("");
    try { await api.request(action.path, { method: "POST", body: action.body, key: action.key }); setPendingActions(all => { const next = { ...all }; delete next[action.projectId]; return next; }); setFeedback(action.label); if (action.path.endsWith("/approvals")) setSelectedReview([]); refresh(); void reloadProjects().catch(() => {}); }
    catch (error) {
      if (!(error instanceof ApiError) || ["NETWORK_ERROR", "INTERNAL_ERROR", "REQUEST_FAILED"].includes(error.code)) setPendingActions(all => ({ ...all, [action.projectId]: action }));
      else { setPendingActions(all => { const next = { ...all }; delete next[action.projectId]; return next; }); if (action.path.endsWith("/approvals")) { setSelectedReview([]); setReviewChanged(true); } }
      setActionError(errorText(error)); refresh();
    } finally { setBusy(false); }
  }
  function demo(action: "create" | "close_up" | "wide") { if (snapshot && demoAvailable) void runAction({ projectId, path: `${projectPath(projectId)}/demo`, body: { action, ...(action === "create" ? {} : { shotId: selectedShots[0] }) }, key: crypto.randomUUID(), label: "Demo request recorded. Follow its progress here." }); }
  function approve() { if (!review || staleReview || busy) return; try { const body = approvalPayload(review, selectedReview, displayed, selectionIdentity.current); void runAction({ projectId, path: `${projectPath(projectId)}/approvals`, body, key: crypto.randomUUID(), label: "Your selected keyframes were approved." }); } catch (error) { setActionError(errorText(error)); } }
  const onDisplayed = useCallback((id: string, sha: string) => { setDisplayed(all => all[id] === sha ? all : { ...all, [id]: sha }); if (!sha) setSelectedReview(ids => ids.filter(item => item !== id)); }, []);
  const toggleScope = (id: string) => { setSelectedShots(ids => ids.includes(id) ? ids.filter(item => item !== id) : [...ids, id]); composer.current?.focus(); };
  const disabled = busy || !!pendingAction || !!pendingMessage;
  const selectedNames = snapshot?.project.shots.filter(shot => selectedShots.includes(shot.id)).map(shot => `Shot ${snapshot.project.shots.indexOf(shot) + 1}`) ?? [];
  const totalFrames = snapshot?.project.shots.reduce((total, shot) => total + shot.desiredFrames, 0) ?? 0;
  const pendingQuestions = snapshot?.questions?.filter(question => question.state === "pending") ?? [];
  const replyQuestion = pendingQuestions.find(question => question.id === replyQuestionId);
  const heldRequests = [...new Set(snapshot?.holds.filter(hold => hold.active).map(hold => hold.ownerId) ?? [])];
  const approvedCount = review?.members.filter(member => member.approved).length ?? 0;
  return <div className="studio-shell">{showDirectorSettings && projectId && <DirectorSettings key={projectId} api={api} projectId={projectId} close={() => setShowDirectorSettings(false)} changed={refresh} />}<aside className="sidebar"><a href="#workspace" className="brand"><span className="brand-mark"><Icon name="slate" /></span>{APP_NAME}</a><span className="sidebar-caption">YOUR LOCAL STUDIO</span><div className="sidebar-section-heading"><h2>Projects</h2><button className="icon-button" onClick={() => setShowNew(value => !value)} aria-label="Create a project" disabled={busy}><Icon name="plus" size={18} /></button></div>
    {showNew && <form className="new-project-form" onSubmit={event => void createProject(event)}><label className="sr-only" htmlFor="project-name">Project name</label><input id="project-name" value={newName} onChange={event => setNewName(event.target.value)} maxLength={160} placeholder="Name your film" disabled={!!pendingCreation} autoFocus /><NewProjectProviderFields api={api} selection={providerSelection} changed={setProviderSelection} disabled={creating || !!pendingCreation} /><button disabled={creating || !newName.trim()} className="button small primary">{creating ? "Creating…" : pendingCreation ? "Retry same project" : "Create project"}</button></form>}
    <nav className="project-list" aria-label="Projects">{projects.map(project => <button key={project.id} className={`project-link ${project.id === projectId ? "active" : ""}`} onClick={() => setProjectId(project.id)} disabled={busy} aria-current={project.id === projectId ? "page" : undefined}><Icon name="folder" size={17} /><span>{project.name}<small>{project.shotCount ? `${project.shotCount} shots` : "A fresh start"}</small></span></button>)}</nav><div className="sidebar-bottom"><div className="local-user"><span className="avatar"><Icon name="slate" size={16} /></span><div><strong>Local workspace</strong><small>Saved on your computer</small></div></div><button className="text-button" disabled={!projectId} onClick={() => setShowDirectorSettings(true)}>Director setup</button><button className="text-button" onClick={disconnect}>Disconnect</button><span className="sidebar-version">OPEN SOURCE · EARLY PREVIEW</span></div></aside>
    <div className="studio-main" id="workspace"><header className="workspace-header"><div><span className="breadcrumb">Workspace <Icon name="chevron" size={12} /></span><h1>{snapshot?.project.name ?? projects.find(project => project.id === projectId)?.name ?? "Your next film"}</h1></div><div className="header-actions">{projectId && <button className="text-button mobile-director" onClick={() => setShowDirectorSettings(true)}>Director setup</button>}<button className="text-button mobile-disconnect" onClick={disconnect}>Disconnect</button><span className={`connection ${connected ? "online" : ""}`} role="status"><span className="status-dot" />{!projectId ? "Local connection" : connected ? "Connected" : connection === "connecting" ? "Connecting" : "Reconnecting"}</span>{projectId && <button className="icon-button" onClick={refresh} aria-label="Refresh project"><Icon name="refresh" size={17} /></button>}</div></header>
    {(connectionError || actionError) && <div className="notice error" role="alert"><span>{actionError || connectionError}</span><button onClick={refresh}>Refresh</button></div>}{pendingAction && <div className="notice warning"><span>This action wasn’t confirmed. Retry the same request to check its outcome.</span><button disabled={busy} onClick={() => void runAction(pendingAction)}>Retry action</button></div>}{feedback && <div className="sr-only" role="status">{feedback}</div>}
    {!projectId ? <main className="empty-studio"><span className="empty-symbol"><Icon name="slate" size={40} /></span><span className="eyebrow">YOUR FIRST SLATE</span><h2>Make room for an idea.</h2><p>Create a project to start a conversation and shape your first storyboard.</p><button className="button primary" onClick={() => setShowNew(true)}><Icon name="plus" size={16} />New project</button></main>
    : <main className="workspace-grid"><section className="conversation-panel" aria-labelledby="conversation-title"><div className="panel-title"><div><Icon name="chat" size={18} /><h2 id="conversation-title">Conversation</h2></div><span className="tag subtle">{director.mode === "fake" ? "Demo director" : director.mode === "native" ? "Codex director" : "Director offline"}</span></div><div className="conversation-stream" aria-live="polite" aria-relevant="additions text"><div className="conversation-intro"><span className="small-mark"><Icon name="slate" size={20} /></span><h3>Let’s shape the story.</h3><p>Talk through your idea here. Select a shot to focus the conversation on that part of the film.</p></div>
    {director.mode === "fake" && <div className="demo-disclosure"><span className="tiny-label">DEMO MODE</span><p>{demoAvailable ? "This director uses canned guidance and fixture media. Ordinary chat does not change the video; use the demo edit buttons below." : "This director uses canned guidance. Set up Codex to plan with this project’s saved models."} Paid image and video generation isn’t enabled yet.</p></div>}{director.mode === "offline" && <div className="demo-disclosure"><p>Your messages are saved. A live director isn’t connected.</p></div>}
    {messages.map(message => <article key={message.id} className={`message ${message.role}`}><div className="message-byline">{message.role === "assistant" ? "OpenSlate" : "You"}</div><p>{message.text}</p>{message.state === "failed" && <small>Response needs attention</small>}</article>)}{pendingMessage && <article className="message user pending"><div className="message-byline">You <span>{pendingMessage.failed ? "Not confirmed" : "Sending…"}</span></div><p>{pendingMessage.command.body.text}</p>{pendingMessage.failed && <button className="text-button" disabled={busy} onClick={() => void send()}>Retry this message</button>}</article>}{director.status === "running" && <div className="director-working" role="status"><span className="working-dots"><i /><i /><i /></span>Working on your request</div>}{director.message && director.status === "error" && <div className="inline-error">{director.message}</div>}{pendingQuestions.map(question => <section key={question.id} className={`question-card ${replyQuestionId === question.id ? "selected" : ""}`} aria-label="OpenSlate question"><span className="tiny-label">YOUR INPUT NEEDED</span>{question.questions.map(item => <div key={item.id}><h3>{item.header}</h3><p>{item.question}</p>{item.options.length > 0 && <ul>{item.options.map(option => <li key={option.label}><strong>{option.label}</strong> — {option.description}</li>)}</ul>}</div>)}<button className="button small" disabled={disabled} onClick={() => { setReplyQuestionId(question.id); composer.current?.focus(); }}>{replyQuestionId === question.id ? "Replying below" : "Answer this question"}</button></section>)}<div ref={chatEnd} /></div>
    <div className="composer-area">{replyQuestion && <div className="scope-chip"><span>Replying to: {replyQuestion.questions.map(item => item.header).join(", ")}</span><button onClick={() => setReplyQuestionId(null)} aria-label="Cancel question reply"><Icon name="close" size={13} /></button></div>}{!replyQuestion && selectedShots.length > 0 && <div className="scope-chip"><Icon name="image" size={14} /><span>{selectedNames.join(", ")}</span><button onClick={() => setSelectedShots([])} aria-label="Clear shot selection"><Icon name="close" size={13} /></button></div>}{director.mode === "fake" && demoAvailable && !replyQuestion && selectedShots.length === 1 && <div className="quick-actions"><span>Try an edit</span><button disabled={disabled || !connected} onClick={() => demo("close_up")}>Close-up</button><button disabled={disabled || !connected} onClick={() => demo("wide")}>Wide shot</button></div>}<form onSubmit={event => { event.preventDefault(); void send(); }} className="composer"><label className="sr-only" htmlFor="message-draft">Message OpenSlate</label><textarea ref={composer} id="message-draft" value={draft} onChange={event => setDrafts(all => ({ ...all, [projectId]: event.target.value }))} placeholder={replyQuestion ? "Your answer to the selected question…" : selectedShots.length ? `What should change in ${selectedNames.join(", ").toLowerCase()}?` : "Tell me about the film you have in mind…"} maxLength={16000} disabled={!!pendingMessage} rows={3} onKeyDown={event => { if ((event.metaKey || event.ctrlKey) && event.key === "Enter") { event.preventDefault(); void send(); } }} /><div className="composer-bottom"><span>{replyQuestion ? "Selected question" : selectedShots.length ? "Selected shots only" : "Whole project"}</span><button className="send-button" disabled={disabled || !draft.trim() || !snapshot} aria-label="Send message"><Icon name="arrow" size={18} /></button></div></form><p className="composer-note">⌘ / Ctrl + Enter to send · Edits stay in the conversation</p></div></section>
    <section className="review-workspace" aria-label="Production workspace"><div className="film-heading"><div><span className="eyebrow">FROM IDEA TO FRAME</span><h2>Your film, taking shape.</h2><p>Review the direction. Refine one shot at a time.</p></div>{snapshot && <div className="film-meta"><strong>{snapshot.project.shots.length}</strong><span>shots</span><i /><strong>{durationLabel(totalFrames)}</strong><span>planned</span></div>}</div><div className="workspace-toolbar"><div className="tabs" aria-label="Workspace views"><button className={tab === "storyboard" ? "active" : ""} onClick={() => setTab("storyboard")} aria-pressed={tab === "storyboard"}>Storyboard <span>{snapshot?.project.shots.length ?? 0}</span></button><button className={tab === "plan" ? "active" : ""} onClick={() => setTab("plan")} aria-pressed={tab === "plan"}>Story & narration</button></div>{snapshot?.control && <button className="button quiet small" disabled={disabled || !connected} onClick={() => void runAction({ projectId, path: `${projectPath(projectId)}/controls`, body: { action: snapshot.control?.paused ? "resume" : "pause" }, key: crypto.randomUUID(), label: snapshot.control?.paused ? "Execution resumed." : "Execution paused." })}><Icon name={snapshot.control.paused ? "play" : "pause"} size={14} />{snapshot.control.paused ? "Resume" : "Pause"}</button>}</div>
    {snapshot?.control?.paused && <div className="notice warning"><span>Execution is paused. You can keep reviewing and discussing the plan.</span></div>}{heldRequests.length > 0 && <div className="hold-list">{heldRequests.map(requestId => <div className="notice warning" key={requestId}><span>A pending edit is holding {new Set(snapshot?.holds.filter(hold => hold.active && hold.ownerId === requestId).map(hold => hold.scopeId)).size} part(s) of this project. Resume does not clear that pending edit.</span>{director.mode === "native" && <button disabled={disabled || !connected} onClick={() => void runAction({ projectId, path: `${projectPath(projectId)}/messages`, body: { text: "Continue this earlier edit using its saved scope and current project state.", scopeIds: snapshot?.holds.filter(hold => hold.active && hold.ownerId === requestId).map(hold => hold.scopeId), continuationRequestId: requestId, editing: true }, key: crypto.randomUUID(), label: "The earlier edit was explicitly continued." })}>Continue this edit</button>}</div>)}</div>}{reviewChanged && <div className="notice warning"><span>The storyboard changed. Review the updated frames and select them again.</span><button onClick={() => setReviewChanged(false)}>Got it</button></div>}
    {!snapshot ? <div className="loading-state"><span className="loading-ring" />Loading your workspace…</div>
    : tab === "plan" ? <div className="story-panels"><section className="story-card"><span className="eyebrow">THE BRIEF</span><h3>What we’re making</h3><p>{snapshot.project.brief || "Start with your idea in the conversation. The settled brief will appear here."}</p></section><section className="story-card"><span className="eyebrow">THE STORY</span><h3>A thread through the film</h3><p>{snapshot.project.story || "Develop the story with OpenSlate before shaping individual shots."}</p></section><section className="story-card narration-card"><span className="eyebrow">NARRATION</span><h3>The voice of the story</h3><span className="tag">{snapshot.workflow?.narration?.inputState?.replaceAll("_", " ") ?? "No audio yet"}</span><p>{snapshot.project.narration.script || "Use the conversation to develop your narration, then review scripts and supplied recordings below. Voice generation is not connected yet."}</p></section></div>
    : snapshot.project.shots.length === 0 ? <div className="empty-storyboard"><div className="empty-frames"><span /><span><Icon name="image" size={32} /></span><span /></div><span className="eyebrow">A BLANK SLATE, FOR NOW</span><h3>Your first frames belong here.</h3><p>Start a conversation about your film, or try the two-shot demo to explore the review flow.</p>{director.mode === "fake" && demoAvailable && <button className="button primary" disabled={disabled || !connected} onClick={() => demo("create")}><Icon name="play" size={15} />Create a 2-shot demo</button>}<small>{demoAvailable ? "The demo uses fixture images and video." : "Use Codex to plan with these saved models. Create a default project to explore the demo."}</small></div>
    : <><div className="review-guidance"><div><span className="review-step">01</span><div><strong>Keyframes first. Video next.</strong><p>Select the displayed frames you approve, including their motion plan.</p></div></div><span className="approval-count">{approvedCount} / {review?.members.length ?? snapshot.project.shots.length} approved</span></div>
    {snapshot.project.scenes.map((scene, sceneIndex) => { const shots = snapshot.project.shots.filter(shot => shot.sceneId === scene.id); if (!shots.length) return null; return <section className="scene-group" key={scene.id}><div className="scene-heading"><span>SCENE {String(sceneIndex + 1).padStart(2, "0")}</span><h3>{scene.purpose}</h3><span>{shots.length} shots</span></div><div className="shot-grid">{shots.map(shot => { const index = snapshot.project.shots.indexOf(shot); const member = review?.members.find(member => member.shotId === shot.id); return <ShotCard key={shot.id} api={api} projectId={projectId} shot={shot} index={index} member={member} chosen={!!member && selectedReview.includes(member.videoNodeId)} scoped={selectedShots.includes(shot.id)} stale={staleReview || disabled} onChoose={() => { selectionIdentity.current = identity; if (member) setSelectedReview(ids => ids.includes(member.videoNodeId) ? ids.filter(id => id !== member.videoNodeId) : [...ids, member.videoNodeId]); setReviewChanged(false); }} onScope={() => toggleScope(shot.id)} onDisplayed={onDisplayed} onEnlarge={(url, shot, fixture) => setLightbox({ url, shot, fixture })} take={snapshot.outputs.find(output => output.nodeId === member?.videoNodeId && output.artifact.kind === "video")} />; })}</div></section>; })}
    <div className="approval-bar"><div><strong>{selectedReview.length ? `${selectedReview.length} keyframe${selectedReview.length === 1 ? "" : "s"} selected` : "Your review sets the direction"}</strong><p>{staleReview ? "Reconnect and refresh before approving." : "Approval covers these exact frames and their motion plans."}</p></div><button className="button primary" disabled={disabled || staleReview || !selectedReview.length} onClick={approve}><Icon name="check" size={17} />Approve {selectedReview.length || "selected"} frame{selectedReview.length === 1 ? "" : "s"}</button></div><p className="fixture-note">{review?.members.some(member => member.keyframeFixture === true) ? "Fixture previews represent pipeline state, not the requested creative quality. Creative improvements remain your choice." : "Review each keyframe and motion plan before creating video."}</p><Preview api={api} snapshot={snapshot} /></>}
    {snapshot && <div hidden={tab !== "plan"}><NarrationPanel api={api} projectId={projectId} headVersion={snapshot.project.headVersion} shots={snapshot.project.shots} directorMode={director.mode} onChanged={refresh} {...(director.mode === "native" ? { onContinue: (requestId: string) => { void runAction({ projectId, path: `${projectPath(projectId)}/messages`, body: { text: "Continue this edit from the saved narration review. Read the accepted canonical cues and supplied assets, explain any remaining gaps, and update only the affected planning work.", scopeIds: [projectId], continuationRequestId: requestId, editing: true }, key: crypto.randomUUID(), label: "Narration planning continued in the conversation." }); } } : {})} /></div>}
    {snapshot && <><SpendingPanel api={api} snapshot={snapshot} onChanged={refresh} /><ImagePanel api={api} snapshot={snapshot} onChanged={refresh} discussDisabled={disabled || !connected} discussionUnavailable={!director.imageAttachmentsAvailable} onDiscuss={director.mode === "native" ? artifact => { const command = makeImageDiscussion(projectId, artifact, crypto.randomUUID()); void runAction({ projectId, path: `${projectPath(projectId)}/messages`, body: command.body, key: command.key, label: "Reference attached to this discussion." }); } : undefined} /></>}
    {snapshot && <MediaPanel key={projectId} api={api} snapshot={snapshot} onChanged={refresh} onContinue={director.mode === "native" ? requestId => { void runAction({ projectId, path: `${projectPath(projectId)}/messages`, body: { text: "Continue this edit using the supplied clips and current narration. Help me plan their order; ask about missing creative choices before applying a plan.", scopeIds: [projectId], continuationRequestId: requestId, editing: true }, key: crypto.randomUUID(), label: "Clip planning continued in the conversation." }); } : undefined} />}
    {snapshot?.plan && <details className="debug-panel"><summary>Plan & technical details <span>For debugging</span></summary><div><p>Plan {snapshot.plan.id} · Revision {snapshot.project.headVersion}</p><p>Graph {snapshot.plan.graphDigest}</p><pre>{snapshot.plan.canonicalSource}</pre></div></details>}</section></main>}
    </div>{lightbox && <Lightbox value={lightbox} onClose={() => setLightbox(null)} />}</div>;
}
export default function App() {
  const [session, setSession] = useState<{ api: StudioApi; projects: ProjectSummary[] } | null>(null);
  useEffect(() => () => session?.api.close(), [session]);
  async function connect(token: string) { const api = new StudioApi(token); try { const response = await api.request<{ projects: ProjectSummary[] }>("/api/projects"); setSession({ api, projects: response.projects }); } catch (error) { api.close(); throw error; } }
  return session ? <Studio api={session.api} initialProjects={session.projects} disconnect={() => setSession(null)} /> : <Connect onConnect={connect} />;
}
