import { useEffect, useRef, useState } from 'react';
import type { ProjectSnapshot, Shot, ReviewMember } from './model';
import type { StudioApi } from './api';
import { Icon, IconButton, useArtifact } from './components';
export type BoardCommand = (body: Record<string, unknown>) => void;
/** Keep focused text and its original revision across SSE updates. */
export function InlineField({ value, label, version, save, multiline = false, disabled = false, className = '' }: { value: string; label: string; version: number; save(value: string, version: number): void; multiline?: boolean; disabled?: boolean; className?: string }) {
  const [draft, setDraft] = useState(value), editing = useRef(false), cancelled = useRef(false), base = useRef({ value, version });
  useEffect(() => { if (!editing.current) { setDraft(value); base.current = { value, version }; } }, [value, version]);
  const props = { value: draft, disabled, 'aria-label': label, className: `board-edit ${className}`, onFocus: () => { cancelled.current = false; editing.current = true; base.current = { value, version }; }, onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setDraft(event.target.value), onBlur: () => { editing.current = false; if (cancelled.current) return; if (draft.trim() !== base.current.value) save(draft.trim(), base.current.version); }, onKeyDown: (event: React.KeyboardEvent<HTMLInputElement | HTMLTextAreaElement>) => { if (event.key === 'Escape') { cancelled.current = true; setDraft(value); editing.current = false; base.current = { value, version }; event.currentTarget.value = value; event.currentTarget.blur(); } else if (event.key === 'Enter' && !multiline) event.currentTarget.blur(); } };
  return multiline ? <textarea {...props} rows={2} /> : <input {...props} />;
}
export function StoryboardShot({ api, snapshot, shot, member, stale, command, onApprove, onDiscuss, onDisplayed, onNarration }: { api: StudioApi; snapshot: ProjectSnapshot; shot: Shot; member?: ReviewMember | undefined; stale: boolean; command: BoardCommand; onApprove(): void; onDiscuss(): void; onDisplayed(id: string, sha: string): void; onNarration(): void }) {
  const id = snapshot.project.id, version = snapshot.project.headVersion;
  const node = snapshot.plan?.nodes?.find(n => n.shotId === shot.id && n.kind === 'video');
  const take = snapshot.outputs.find(x => x.nodeId === node?.id && x.artifact.kind === 'video');
  const imageOutput = snapshot.outputs.find(x => snapshot.plan?.nodes?.some(n => n.id === x.nodeId && n.shotId === shot.id && n.kind === 'image'));
  const frame = member?.keyframe ?? imageOutput?.artifact, frameFixture = member?.keyframe ? member.keyframeFixture : imageOutput?.fixture;
  const still = useArtifact(api, id, frame ?? null), clip = useArtifact(api, id, take?.artifact ?? null);
  const video = useRef<HTMLVideoElement>(null), [loaded, setLoaded] = useState(false);
  const sceneIndex = snapshot.project.scenes.findIndex(x => x.id === shot.sceneId), local = snapshot.project.shots.filter(x => x.sceneId === shot.sceneId), index = local.findIndex(x => x.id === shot.id), label = `${sceneIndex + 1}.${index + 1}`;
  useEffect(() => { setLoaded(false); if (member) onDisplayed(member.videoNodeId, ''); return () => { if (member) onDisplayed(member.videoNodeId, ''); }; }, [still.url, member?.videoNodeId, onDisplayed]);
  const edit = (field: string, value: string, expectedHeadVersion: number) => command({ kind: 'shot', id: shot.id, field, value, expectedHeadVersion });
  const narration = shot.narration;
  return <article className="board-shot" aria-label={`Shot ${label}: ${shot.purpose}`} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); e.stopPropagation(); if (stale) return; const source = e.dataTransfer.getData('text/openslate-shot'); if (source && source !== shot.id) { const box = e.currentTarget.getBoundingClientRect(); const following = local.slice(index + 1).find(s => s.id !== source); const beforeId = e.clientX < box.left + box.width / 2 ? shot.id : following?.id; command({ kind: 'moveShot', id: source, sceneId: shot.sceneId, ...(beforeId ? { beforeId } : {}) }); } }}>
    <div className="board-media">{clip.url ? <video ref={video} src={clip.url} poster={still.url ?? undefined} controls playsInline preload="metadata" aria-label={`Video for shot ${label}`} onPointerEnter={() => { if (!matchMedia('(prefers-reduced-motion: reduce)').matches && video.current) { video.current.muted = true; void video.current.play().catch(() => {}); } }} onPointerLeave={() => video.current?.pause()} /> : still.url ? <img src={still.url} alt={`Keyframe for shot ${label}`} onLoad={() => { setLoaded(true); if (member?.keyframe) onDisplayed(member.videoNodeId, member.keyframe.sha256); }} onError={() => { setLoaded(false); if (member) onDisplayed(member.videoNodeId, ''); }} /> : <div className="board-placeholder"><Icon name="image" size={30} /><span>{still.error || clip.error ? 'Media unavailable' : 'Keyframe to create'}</span></div>}
      <button className="board-grip" disabled={stale} draggable={!stale} aria-label={`Move shot ${label}. Drag or use Alt and arrow keys`} title="Drag to reorder · Alt + arrow keys" onDragStart={e => e.dataTransfer.setData('text/openslate-shot', shot.id)} onKeyDown={e => { if (!e.altKey || !['ArrowLeft','ArrowRight'].includes(e.key)) return; e.preventDefault(); const target = e.key === 'ArrowLeft' ? local[index - 1] : local[index + 2]; if (e.key === 'ArrowLeft' && !target || e.key === 'ArrowRight' && index === local.length - 1) return; command({ kind: 'moveShot', id: shot.id, sceneId: shot.sceneId, ...(target ? { beforeId: target.id } : {}) }); }}>⠿ {label}</button>
      <IconButton className="board-delete" label={`Delete shot ${label}`} disabled={stale} onClick={() => command({ kind: 'deleteShot', id: shot.id })} />
      <span className="board-media-state">{take ? take.fixture ? 'Video · fixture' : 'Video' : frame ? frameFixture ? 'Keyframe · fixture' : 'Keyframe' : 'No keyframe'}</span>
      <label className="board-duration"><InlineField value={String(shot.desiredFrames / 30)} label={`Shot ${label} seconds`} version={version} disabled={stale} save={(v, ver) => edit('desiredFrames', String(Number(v) * 30), ver)} />s</label>
    </div>
    <div className="board-shot-body"><InlineField className="board-shot-title" value={shot.purpose} label={`Shot ${label} title`} version={version} disabled={stale} save={(v, ver) => edit('purpose', v, ver)} /><InlineField value={shot.motion} label={`Shot ${label} camera movement`} version={version} disabled={stale} save={(v, ver) => edit('motion', v, ver)} />
      <div className="board-direction"><span>Direction</span><InlineField multiline value={shot.framing} label={`Shot ${label} direction`} version={version} disabled={stale} save={(v, ver) => edit('framing', v, ver)} /></div>
      <div className="board-shot-footer"><select aria-label={`Narration for shot ${label}`} value={narration?.mode ?? 'undecided'} disabled={stale} onChange={e => command({ kind: 'narration', id: shot.id, field: 'mode', value: e.target.value })}><option value="undecided" disabled>Narration…</option><option value="none">No narration</option><option value="generated">Generate voice</option><option value="uploaded">Upload recording</option></select><IconButton icon="chat" label={`Discuss shot ${label}`} onClick={onDiscuss} /><button className={`icon-button board-review ${member?.approved ? 'approved' : ''}`} aria-label={member?.approved ? `Shot ${label} reviewed` : `Approve shot ${label} keyframe and motion`} title={member?.approved ? 'Reviewed' : 'Approve exact keyframe and motion'} disabled={stale || !!member?.approved || !loaded || !member?.ready} onClick={onApprove}><Icon name="check" size={16} /></button></div>
      {narration && !['none','undecided'].includes(narration.mode) && <div className="board-narration">{narration.mode === 'generated' && <><InlineField multiline value={narration.text} label={`Shot ${label} narration script`} version={version} disabled={stale} save={(value, expectedHeadVersion) => command({ kind: 'narration', id: shot.id, field: 'text', value, expectedHeadVersion })} /><select aria-label={`Voice for shot ${label}`} value={narration.voice} disabled={stale} onChange={e => command({ kind: 'narration', id: shot.id, field: 'voice', value: e.target.value })}><option value="stock">Provider voice</option><option value="personal">My recorded voice (setup required)</option></select></>}<div className="board-narration-status"><small>{narration.mode === 'generated' ? 'Writing intent · audio review required' : 'Attach and review a recording'}</small><IconButton icon="settings" label={`Audio setup for shot ${label}`} onClick={onNarration} /></div></div>}
      {narration?.mode === 'none' && shot.cueId && <small className="board-profile">Removal requested · saved audio changes after narration review</small>}
      {!take && member?.profileLabel && <small className="board-profile">{member.profileLabel} · {member.motionPrompt}</small>}
    </div>
  </article>;
}
